# Generated by Django 5.2.1 on 2025-05-24 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_mensajecontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='link',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('produccion', '🟢 En Producción'), ('beta', '🟣 En Beta'), ('desarrollo', '🟡En Desarrollo'), ('finalizado', '🔴 Finalizado')], default='desarrollo', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(default='Sin especificar', max_length=255),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('web', '🌐 Aplicación Web'), ('escritorio', '🖥️ Sotfware de Escritorio'), ('movil', '📱 Aplicación Móvil'), ('ai', '🤖 Asistente Virtual')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='version',
            field=models.CharField(default=1.0, max_length=10),
        ),
    ]
