# Generated by Django 5.2.1 on 2025-06-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_proyecto_link_proyecto_enlace_proyecto_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('planeado', '🔴 Planeado'), ('progreso', '🟡 En progreso'), ('completado', '🟢 Completado')], default='planeado', max_length=20)),
                ('progreso', models.IntegerField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
